### ISSUE TITLE
template issue

### ISSUE THREAD

**Issue by steffdixon2010** [digitalninja-ro/klipper-neopixel#1]
this is the code i send.
NEOPIXEL_DISPLAY LED=coolant_fan_ring TEMPLATE=led_extruder_temp

this is the response i get from klipper
Unknown command:"SET_LED_TEMPLATE"

what am i doing wrong lol?

**Comment by eivinboy** [comment]
Have you updated klipper? as the SET_LED_TEMPLATE command is quite new.

**Comment by digitalninja-ro** [comment]
@steffdixon2010 did it work?

**Comment by steffdixon2010** [comment]
@digitalninja-ro yes it did. I hate doing updates as they take so long.
