### ISSUE TITLE
Can't change LED type after print

### ISSUE THREAD

**Issue by vellkan** [digitalninja-ro/klipper-neopixel#11]
Hello
I've install You Neopixel effects and it's works like a charm, except that I can't change this after end of print.
In start print macro I've put that code:
NEOPIXEL_DISPLAY LED="chamber_leds" TYPE=print_percent MODE=progress
And after that I can't change led light - not from g-code, not from Mainsail panel.
I would like to reset that and turn on only white led on present print :)

**Comment by digitalninja-ro** [comment]
Hi, sorry for the late answer, holidays time. 
Please use the [beta](https://github.com/digitalninja-ro/klipper-neopixel/tree/beta) version where I implemented the [CLEAR](https://github.com/digitalninja-ro/klipper-neopixel/tree/beta#clear-template) option.
