### ISSUE TITLE
how to cancel the progress?

### ISSUE THREAD

**Issue by gamevyo** [digitalninja-ro/klipper-neopixel#14]
Thanks for this great piece of software! I like it very much!
I want to know that how to cancel a started printing progress and turn off the leds?

**Comment by digitalninja-ro** [comment]
Use beta version and call [CLEAR](https://github.com/digitalninja-ro/klipper-neopixel/tree/beta#clear-template) command.

**Comment by gamevyo** [comment]
It`s righteous! Thanks a lot!
