### ISSUE TITLE
Reversing order

### ISSUE THREAD

**Issue by srbjessen** [digitalninja-ro/klipper-neopixel#16]
Hi, Love the functionality.

BUT, I'm lucky enough to own a printer that came with neopixels, that were mounted starting from right to left. 
This kinda screws up the progress bar running the opposite direction of "convention".

I have searched the internet dry and tried multiple solutions to reverse the "for" loop, but it always gives me an error when trying to load the cfg.
Is there a super easy way, that i just didn't find, to do this?

**Comment by digitalninja-ro** [comment]
Hi,

It's not just a matter of reverse the "for" loop. The leds are indexed from 1 to total_leds and each led glows different depending of its position. To revers the order I must rewrite the whole macro. It's just a progress bar, not a text, doesn't rely matter if it starts from left or right. :)

**Comment by srbjessen** [comment]
No problem. Solved it with a simple INDEX={my_neopixel.chain_count|int-i}
