### ISSUE TITLE
CANCEL_PRINT issue

### ISSUE THREAD

**Issue by pacnsave** [digitalninja-ro/klipper-neopixel#19]
once cancel print is sent there is no way to clear the template. basically I am using the neopixels on the BTT mini12864 with this macro, once I cancel print the backlight then turns off so I need a way to clear the current template. everything else works correctly

**Comment by digitalninja-ro** [comment]
Use the [Clear Template](https://github.com/digitalninja-ro/klipper-neopixel/tree/beta#clear-template) from [beta version](https://github.com/digitalninja-ro/klipper-neopixel/blob/beta/led_progress.cfg) in your cancel or end macro.

**Comment by pacnsave** [comment]
I have tried that, the problem is mainsail.cfg is a read only file (designed this way) and there is options to customize it, and adding the clear template to the gcode doesn't work

**Comment by digitalninja-ro** [comment]
You need to add the clear cod to your end or cancel macro. You should be able to edit these macros.
