### ISSUE TITLE
Unknown LED error

### ISSUE THREAD

**Issue by eivinboy** [digitalninja-ro/klipper-neopixel#2]
Im just getting (Unknown LED error) pictures below showing both printer.cfg and led_progress.cfg
![146162d02ebb83899e156d8ea446108d](https://user-images.githubusercontent.com/60885771/164791623-bddd6e9d-7e91-4e0e-a32b-98c4c26306b2.png)
![c65ad17462fc5dcb7c01b4c2e68857db](https://user-images.githubusercontent.com/60885771/164791634-0e7abe7e-6573-41e4-aad5-f9b5e3c6acb7.png)
.

**Comment by digitalninja-ro** [comment]
Try to rename from led to my_led
`[neopixel my_led]`

**Comment by eivinboy** [comment]
As seen below i did what you said but now im getting this error ( {'message': "Malformed command 'SET_LED_TEMPLATE LED={'pin': 'PB0', 'chain_count': '61', 'initial_red': '1.0', 'initial_green': '0.0', 'initial_blue': '1.0', 'color_order': 'GRB'} INDEX=1 TEMPLATE= param_led_num=1 param_led_total=20'", 'error': 'WebRequestError'} 
![f52be9ff19aacb74808df355e7237597](https://user-images.githubusercontent.com/60885771/164893514-c8975836-85a1-4ec5-b780-59e02920af67.png)
![0bb10be04ac5e331a6008b6363a5b343](https://user-images.githubusercontent.com/60885771/164893518-e21bfe10-97cb-4659-a6c6-7e41adeeca02.png)
)

**Comment by digitalninja-ro** [comment]
Now I undertand what is happening. Try to rename your pixel
`[neopixel led_chain]`

And call it with
`NEOPIXEL_DISPLAY LED=led_chain TEMPLATE=led_extruder_temp`

My initial recommendation was wrong because I use the same variable name. I'll modify this in the next version.
