### ISSUE TITLE
Brightness control while print_percent / progress

### ISSUE THREAD

**Issue by vjeko2404** [digitalninja-ro/klipper-neopixel#21]
Hello,

is it possible to implement the brightness parameter into some of the types?
I would really want to be able to set the brightness (and even the color) in the print_percent / progress.
For the glow its almost clear, that such parameter would influence the color contrast. But on the progress it should be a option.

Thank you for your time and this great macro!

**Comment by digitalninja-ro** [comment]
One of the main goals was to keep this macro as simple as possible.
