### ISSUE TITLE
How to clear/stop the effect

### ISSUE THREAD

**Issue by N0edL** [digitalninja-ro/klipper-neopixel#24]
Greate repo but how to stop/clear the effect

**Comment by digitalninja-ro** [comment]
Use the [beta](https://github.com/digitalninja-ro/klipper-neopixel/blob/beta/led_progress.cfg) version where I implemented the [clear](https://github.com/digitalninja-ro/klipper-neopixel/tree/beta?tab=readme-ov-file#clear-template) template.

**Comment by N0edL** [comment]
Oke, greate
Another question: How could i make it set the temp glow when a extruder get sets to a target temp?
