### ISSUE TITLE
Beta clear function blocks static setting

### ISSUE THREAD

**Issue by dlettiere** [digitalninja-ro/klipper-neopixel#25]
Firstly, great tool, works awesome. Thanks for the beta version as well, I found that the clear function was blocking my macros from setting lights to static color. I use a RGBW to illuminate the nozzle area and want to set it to  dim white during print but glow during heat up. I also wanted to set my bed lights to static dim red.  I could still manually set them in the console. 

I found that either commenting out Line 25 or adding SYNC=0 TRANSMIT=1 fixes it. I went with the TRANSMIT tag in the event that I am not immediately setting the light after clear.

[gcode_macro NEOPIXEL_DISPLAY]
.....
    {% if type == 'clear' %}
        SET_LED_TEMPLATE LED={led} TEMPLATE=""
        SET_LED LED={led} RED=0 GREEN=0 BLUE=0  SYNC=0 TRANSMIT=1
    {% else %}
......

**Comment by digitalninja-ro** [comment]
Hi,
Thank you for your input. I have 3 neopixel leds on my printer and I didn't have any problem with clear function. For example these commands are from my END_PRINT macro and works perfect:
<img width="462" alt="image" src="https://github.com/user-attachments/assets/75eb5e81-8b3b-4877-8b60-6348ce30c1ee">
