### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by avense** [digitalninja-ro/klipper-neopixel#3]
Section 'display_template led_extruder_temp_progress' is not a valid config section

**Comment by digitalninja-ro** [comment]
You must update to the last version of klipper.

**Comment by avense** [comment]
> You must update to the last version of klipper.

my friend
![image](https://user-images.githubusercontent.com/15719937/165890933-df4f2d32-7dae-475b-9b44-e076d836cdab.png)

**Comment by digitalninja-ro** [comment]
My dear friend,

1. I don't know if my macro works with led_effect. I didn't tested.
2. display_template is a valid configuration section in [klipper](https://www.klipper3d.org/Config_Reference.html#display_template).
3. Did you use the last version of [led_progress.cfg](https://github.com/digitalninja-ro/klipper-neopixel/blob/master/led_progress.cfg)? 
4. Did you save the file in klipper_config folder? How do you included it?
5. How did you call the macro? With what parameters?

Please help me to identify the problem.

Thank you

**Comment by digitalninja-ro** [comment]
@avense - any news?
