### ISSUE TITLE
Congratulations very super works.

### ISSUE THREAD

**Issue by AntoszHUN** [digitalninja-ro/klipper-neopixel#4]
However, I have a question. How can I set all LEDs to light up white after printing starts and green when printing is complete?

**Comment by digitalninja-ro** [comment]
Thank you. Help me a little understand your question. Do you want the led to be white when printing start and become green as print finish? Which transition: glow or progress?

**Comment by AntoszHUN** [comment]
> 



> Thank you. Help me a little understand your question. Do you want the led to be white when printing start and become green as print finish? Which transition: glow or progress?

Hi! Exactly as you wrote. Continuous lighting. All LEDs should light white and then turn green at the end of printing.

**Comment by digitalninja-ro** [comment]
The scope of the macro is to use a neopixel led as a progress bar. If you want your led to be white the whole printing process and turn green only when print ends use a simple SET_LED command in your START and END macros.

In START macro add
`SET_LED LED=led_name RED=1 GREEN=1 BLUE=1`

In END macro add
`SET_LED LED=led_name RED=0 GREEN=1 BLUE=0`

**Comment by AntoszHUN** [comment]
> 



> The scope of the macro is to use a neopixel led as a progress bar. If you want your led to be white the whole printing process and turn green only when print ends use a simple SET_LED command in your START and END macros.
> 
> In START macro add `SET_LED LED=led_name RED=1 GREEN=1 BLUE=1`
> 
> In END macro add `SET_LED LED=led_name RED=0 GREEN=1 BLUE=0`

Yes. I tried this. Did not work. 1 LED was lit white and the rest remained red. Then, at the end of the print, it turned blue.

**Comment by digitalninja-ro** [comment]
You can use either one or the other - my macro or the commends above. Not both in the same time. As soon as you set a template to a led, SET_LED will not work.

**Comment by AntoszHUN** [comment]
> 



> You can use either one or the other - my macro or the commends above. Not both in the same time. As soon as you set a template to a led, SET_LED will not work.

So should the SET_LED command be used as the macro after the template?

**Comment by digitalninja-ro** [comment]
Just use the SET_LED command. Don't use any of my macro template! If you use them the LED_SET command will not work.

**Comment by AntoszHUN** [comment]
I mean, if I use the NEOPIXEL_DISPLAY LED = NeoPixel TYPE = extruder_temp MODE = glow command in GCODE_MACRO, I can't use these commands.
SET_LED LED = NeoPixel RED = 0 GREEN = 0 BLUE = 0
SET_LED LED = NeoPixel RED = 1 GREEN = 1 BLUE = 1

Then the stunt won't go on here. :(
What can be done?

**Comment by AntoszHUN** [comment]
The problem is still unresolved. When the bed heats up and the nozzle lights up red during printing. How do I set it to be white by the end of printing?
