### ISSUE TITLE
Error after restart

### ISSUE THREAD

**Issue by bamedley1995** [digitalninja-ro/klipper-neopixel#6]
I followed the Doc instructions and after restart i get this error "Option '{% if mode' is not valid in section 'gcode_macro neopixel_display'"

**Comment by digitalninja-ro** [comment]
Hi,

Please provide some more info:
1. Your [neopixel] section from cfg
2. Did you include the led_progress.cfg into your printer.cfg?
3. How did you call the NEOPIXEL_DISPLAY macro? What parameters?

**Comment by digitalninja-ro** [comment]
After 5 days I assume @bamedley1995 did find the solution or give up.

**Comment by Sonicboom247** [comment]
@digitalninja-ro any chance you can offer an example of how the macro should look?  I too have been getting Option 'led' is not valid in section 'gcode_macro neopixel_display', some of us are new to this type of coding and the simplest indent can cause issues.
[gcode_macro NEOPIXEL_DISPLAY]
LED="my_neopixel" TYPE=extruder_temp MODE=glow
 i thought = was replaced with :

**Comment by Sonicboom247** [comment]
looks like, this is all it needed, leaving here for any others suffering through this
[gcode_macro NEOPIXEL_DISPLAY]
gcode:
 LED="my_neopixel" TYPE=extruder_temp MODE=glow
