### ISSUE TITLE
Keep getting errors

### ISSUE THREAD

**Issue by zcohen-nerd** [digitalninja-ro/klipper-neopixel#7]
Hello,
Thanks so much for taking the time to write this code and post it publicly.
If you dont mind, I was hoping you could help me. Whenever I set it up I get the error "Option 'neopixel_display led' is not valid in section 'gcode_macro led_change'"
Here is my LED section:
![image](https://user-images.githubusercontent.com/61070171/177055690-0780ea74-0f4c-4601-b1b4-7e1beaa4b5c5.png)

Here is my macro section:
![image](https://user-images.githubusercontent.com/61070171/177055718-4da0043f-debb-40a8-a82e-f7f8583229f2.png)

If you can help me I'd really appreciate it. This is my first use of a new macro and so I'm trying to learn how to implement them myself.

**Comment by Sonicboom247** [comment]
you need to indent the actual code like so, trust me gets me every time....![Screenshot from 2022-07-05 23-25-24](https://user-images.githubusercontent.com/84334417/177461665-41a68548-c92f-496d-a910-063616883b31.png)

**Comment by zcohen-nerd** [comment]
Yep, that fixed it. Thank  you!

**Comment by Sonicboom247** [comment]
no worries!, lol now mine is broken, only way i can get it to work is by manually sending NEOPIXEL_DISPLAY LED=my_neopixel TYPE=extruder_temp MODE=glow... 
correction, added a separate entry for START_PRINT and it turned off the Neopixels so it did something...lol
